/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ti2.pkg2cybernube.Usuario;
/**
 *
 * @author ezequ
 */
public class frmUsuarioF extends javax.swing.JFrame {

    Usuario user = new Usuario();
    /**
     * Creates new form frmUsuarioF
     */
    public frmUsuarioF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlConsultarDatos = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtIdUsuario = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNombreUsuarioB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cboRolB = new javax.swing.JComboBox<>();
        btnBuscard = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnCambiarEstado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuario = new javax.swing.JTable();
        pnlConsultarDatos1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtIdUsuario1 = new javax.swing.JTextField();
        btnBuscar1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtNombreUsuarioB1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cboRolB1 = new javax.swing.JComboBox<>();
        btnBuscard1 = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnCambiarEstado1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuario1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboRol = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlConsultarDatos2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtIdUsuarioB = new javax.swing.JTextField();
        btnBuscarld = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtNombreUsuarioB2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        btnBuscard2 = new javax.swing.JButton();
        btnModificar2 = new javax.swing.JButton();
        btnCambiarEstado2 = new javax.swing.JButton();
        tblUsuario3 = new javax.swing.JScrollPane();
        tblUsuario2 = new javax.swing.JTable();
        cboRolB3 = new javax.swing.JComboBox<>();
        lblIdUsuario = new javax.swing.JLabel();

        pnlConsultarDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Usuarios"));

        jLabel9.setText("ID USUARIO");

        btnBuscar.setText("BUSCAR");

        jLabel10.setText("NOMBRE");

        jLabel11.setText("ROL");

        cboRolB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "Item 2", "Item 3", "Item 4" }));
        cboRolB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRolBActionPerformed(evt);
            }
        });

        btnBuscard.setText("BUSCAR");

        btnModificar.setText("MODIFICAR");

        btnCambiarEstado.setText("CAMBIAR ESTADO");

        jScrollPane1.setToolTipText("");
        jScrollPane1.setHorizontalScrollBar(null);

        tblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CELULAR", "EMAIL", "ROL", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuario);

        pnlConsultarDatos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Consulta de Usuarios"));

        jLabel12.setText("ID USUARIO");

        btnBuscar1.setText("BUSCAR");

        jLabel13.setText("NOMBRE");

        jLabel14.setText("ROL");

        cboRolB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "Item 2", "Item 3", "Item 4" }));
        cboRolB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRolB1ActionPerformed(evt);
            }
        });

        btnBuscard1.setText("BUSCAR");

        btnModificar1.setText("MODIFICAR");

        btnCambiarEstado1.setText("CAMBIAR ESTADO");

        jScrollPane2.setToolTipText("");
        jScrollPane2.setHorizontalScrollBar(null);

        tblUsuario1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CELULAR", "EMAIL", "ROL", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblUsuario1);

        javax.swing.GroupLayout pnlConsultarDatos1Layout = new javax.swing.GroupLayout(pnlConsultarDatos1);
        pnlConsultarDatos1.setLayout(pnlConsultarDatos1Layout);
        pnlConsultarDatos1Layout.setHorizontalGroup(
            pnlConsultarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarDatos1Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnModificar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCambiarEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(pnlConsultarDatos1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlConsultarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarDatos1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2))
                    .addGroup(pnlConsultarDatos1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(31, 31, 31)
                        .addComponent(txtIdUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13)
                        .addGap(31, 31, 31)
                        .addComponent(txtNombreUsuarioB1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(cboRolB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnBuscard1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlConsultarDatos1Layout.setVerticalGroup(
            pnlConsultarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarDatos1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlConsultarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtIdUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1)
                    .addComponent(jLabel13)
                    .addComponent(txtNombreUsuarioB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cboRolB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscard1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultarDatos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout pnlConsultarDatosLayout = new javax.swing.GroupLayout(pnlConsultarDatos);
        pnlConsultarDatos.setLayout(pnlConsultarDatosLayout);
        pnlConsultarDatosLayout.setHorizontalGroup(
            pnlConsultarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarDatosLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(pnlConsultarDatosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlConsultarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultarDatosLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addGroup(pnlConsultarDatosLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10)
                        .addGap(31, 31, 31)
                        .addComponent(txtNombreUsuarioB, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cboRolB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnBuscard, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(pnlConsultarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlConsultarDatosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlConsultarDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlConsultarDatosLayout.setVerticalGroup(
            pnlConsultarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarDatosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlConsultarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreUsuarioB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cboRolB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscard))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlConsultarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(pnlConsultarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlConsultarDatosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlConsultarDatos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ezequ\\Downloads\\EsteEsElBueno.png")); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Registro de Usuario.");

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email:");

        txtNombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtNombreUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtNombreUsuario.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre:");

        txtCelular.setBackground(new java.awt.Color(255, 255, 255));
        txtCelular.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtCelular.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Rol:");

        cboRol.setBackground(new java.awt.Color(255, 255, 255));
        cboRol.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cboRol.setForeground(new java.awt.Color(51, 51, 51));
        cboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Ventas", "Compras" }));
        cboRol.setSelectedIndex(-1);

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Celular:");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ID:");

        btnRegistrar.setBackground(new java.awt.Color(0, 102, 204));
        btnRegistrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 102, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlConsultarDatos2.setBackground(new java.awt.Color(255, 255, 255));
        pnlConsultarDatos2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Consulta de Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Black", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(205, 205, 205));
        jLabel15.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("ID USUARIO:");

        txtIdUsuarioB.setBackground(new java.awt.Color(255, 255, 255));
        txtIdUsuarioB.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdUsuarioB.setForeground(new java.awt.Color(0, 0, 0));

        btnBuscarld.setBackground(new java.awt.Color(205, 205, 205));
        btnBuscarld.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBuscarld.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscarld.setText("BUSCAR");
        btnBuscarld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarldActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(205, 205, 205));
        jLabel16.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("NOMBRE:");

        txtNombreUsuarioB2.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreUsuarioB2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombreUsuarioB2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel17.setBackground(new java.awt.Color(205, 205, 205));
        jLabel17.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("ROL:");

        btnBuscard2.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscard2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBuscard2.setForeground(new java.awt.Color(0, 0, 0));
        btnBuscard2.setText("BUSCAR");
        btnBuscard2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscard2ActionPerformed(evt);
            }
        });

        btnModificar2.setBackground(new java.awt.Color(0, 102, 204));
        btnModificar2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnModificar2.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar2.setText("MODIFICAR");
        btnModificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar2ActionPerformed(evt);
            }
        });

        btnCambiarEstado2.setBackground(new java.awt.Color(0, 102, 204));
        btnCambiarEstado2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCambiarEstado2.setForeground(new java.awt.Color(255, 255, 255));
        btnCambiarEstado2.setText("CAMBIAR ESTADO");
        btnCambiarEstado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarEstado2ActionPerformed(evt);
            }
        });

        tblUsuario3.setBackground(new java.awt.Color(255, 255, 255));
        tblUsuario3.setForeground(new java.awt.Color(0, 0, 0));
        tblUsuario3.setToolTipText("");
        tblUsuario3.setHorizontalScrollBar(null);

        tblUsuario2.setBackground(new java.awt.Color(255, 255, 255));
        tblUsuario2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tblUsuario2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "CELULAR", "EMAIL", "ROL", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuario3.setViewportView(tblUsuario2);

        cboRolB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Administrador", "Ventas", "Compras" }));
        cboRolB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboRolB3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlConsultarDatos2Layout = new javax.swing.GroupLayout(pnlConsultarDatos2);
        pnlConsultarDatos2.setLayout(pnlConsultarDatos2Layout);
        pnlConsultarDatos2Layout.setHorizontalGroup(
            pnlConsultarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultarDatos2Layout.createSequentialGroup()
                .addGroup(pnlConsultarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlConsultarDatos2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(tblUsuario3))
                    .addGroup(pnlConsultarDatos2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdUsuarioB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btnBuscarld, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreUsuarioB2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(cboRolB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscard2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 98, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlConsultarDatos2Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(btnModificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnCambiarEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultarDatos2Layout.setVerticalGroup(
            pnlConsultarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlConsultarDatos2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlConsultarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtIdUsuarioB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarld)
                    .addComponent(jLabel16)
                    .addComponent(txtNombreUsuarioB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(btnBuscard2)
                    .addComponent(cboRolB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlConsultarDatos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCambiarEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lblIdUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlConsultarDatos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail)
                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cboRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblIdUsuario))
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboRol, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1)))
                .addGap(47, 47, 47)
                .addComponent(pnlConsultarDatos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// </editor-fold>                        

    //Metodo para vaciar los textField
    private void limpiarDatos(){
        txtNombreUsuario.setText("");
        txtEmail.setText("");
        txtCelular.setText("");
        cboRol.setSelectedIndex(-1);
        txtNombreUsuario.requestFocusInWindow();
        lblIdUsuario.setText("");
    }
    
     
    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
           
        try {
            // obtener los valores de los componentes que escribió el usuario
            String nombreUsuario = txtNombreUsuario.getText();
            String email = txtEmail.getText();
            String celular = txtCelular.getText();
            String rol = cboRol.getSelectedItem().toString();
            // crear un usuario con los 4 valores mínimos solicitados
            user = new Usuario(nombreUsuario, celular, email, rol);
            /* si la etiqueta (label) del id del usuario está vacía significa que no
            se va a modificar un usuario, lo que se quiere hacer es registrar uno nuevo
            */
            if (lblIdUsuario.getText().isEmpty()){
                // crear un nuevo usuario
                /* como ya se mencionó en la clase Usuario, el método al ejecutar un Insert Into
                retorna un valor entero. Lo que se está haciendo es preguntar si es diferente a cero, 
                esto indica que si se inserto. Si diera 0 es que la operación no fue exitosa.
                */
                
                if (user.crear() != 0)
                    JOptionPane.showMessageDialog(null, "Usuario registrado");
                else
                    JOptionPane.showMessageDialog(null, "Usuario no fue posible registrar");
            } else{
                /* al dar falso la pregunta del label, es porque se quiere modificar un usuario,
                entonces, se toma el valor del label para conocer el id del usuario a modificar
                */
                int idUsuario = Integer.parseInt(lblIdUsuario.getText());
                
                if (user.modificar(idUsuario) != 0)
                    JOptionPane.showMessageDialog(null, "Usuario modificado");
                else
                    JOptionPane.showMessageDialog(null, "Usuario no fue posible modificar");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Favor de verificar estén correctos y completos los datos del Usuario. Error: " + ex);
        }
        // método para vaciar los componentes
        limpiarDatos();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
    limpiarDatos();  
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cboRolBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRolBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRolBActionPerformed

    private void cboRolB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRolB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRolB1ActionPerformed

    private void btnBuscard2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscard2ActionPerformed
    // se toman los dos valores de los elementos para buscar en la BD
    String nombreUsuario = txtNombreUsuarioB.getText();
    String rol = cboRolB.getSelectedItem().toString();
    /* se utiliza el método leer de Usuario, este devuelve el modelo ya listo 
    para asignarse al componente JTable
    */
    DefaultTableModel modelo = user.leer(nombreUsuario, rol);
    tblUsuario.setModel(modelo);
                   // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscard2ActionPerformed

    private void btnBuscarldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarldActionPerformed
        // consulta de usuarios sólo con el id
    int idUsuario = Integer.parseInt(txtIdUsuarioB.getText());
    DefaultTableModel modelo = user.leer(idUsuario);
    tblUsuario.setModel(modelo);    
    }//GEN-LAST:event_btnBuscarldActionPerformed

    private void btnModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar2ActionPerformed
    try{
            /* al seleccionar un registro en el JTable y el usuario presiona el botón modificar
            se van a asignar a los elementos del primer panel para ser modificados y después para 
            guardar los cambios se debe dar clic en botón Registrar
            */
            DefaultTableModel modelo = (DefaultTableModel) tblUsuario.getModel();
            /* para obtener un valor de una celda del JTable se utiliza este método, el primer 
            argumento es el número de la fila (row) por ello se indica que será la fila seleccionada
            y para el segundo argumento se indica la columna, estás inician desde 0
            */
            lblIdUsuario.setText(modelo.getValueAt(tblUsuario.getSelectedRow(), 0).toString());
            txtNombreUsuario.setText(modelo.getValueAt(tblUsuario.getSelectedRow(), 1).toString());
            txtCelular.setText(modelo.getValueAt(tblUsuario.getSelectedRow(), 2).toString());
            txtEmail.setText(modelo.getValueAt(tblUsuario.getSelectedRow(), 3).toString());
            cboRol.setSelectedItem(modelo.getValueAt(tblUsuario.getSelectedRow(), 4).toString());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Favor de seleccionar el usuario en la tabla. Error: " + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificar2ActionPerformed

    private void btnCambiarEstado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarEstado2ActionPerformed
    try{
            DefaultTableModel modelo = (DefaultTableModel) tblUsuario.getModel();
            int IdUsuario = Integer.parseInt(modelo.getValueAt(tblUsuario.getSelectedRow(), 0).toString());
            Object estado = modelo.getValueAt(tblUsuario.getSelectedRow(), 5);
            if (user.suspender(IdUsuario, estado) != 0)
                JOptionPane.showMessageDialog(null, "Cambió el Estado del Usuario");
            else
                JOptionPane.showMessageDialog(null, "No fue posible realizar el cambio del estado al Usuario");
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Favor de seleccionar el usuario en la tabla. Error: " + e);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarEstado2ActionPerformed

    private void cboRolB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboRolB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboRolB3ActionPerformed
    private void formWindowClosing(java.awt.event.WindowEvent evt) {                                   
        // al estarse cerrando el formulario se cierra la conexión a la BD
        try {
            user.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(frmUsuarioF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuarioF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuarioF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuarioF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuarioF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuarioF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnBuscard;
    private javax.swing.JButton btnBuscard1;
    private javax.swing.JButton btnBuscard2;
    private javax.swing.JButton btnBuscarld;
    private javax.swing.JButton btnCambiarEstado;
    private javax.swing.JButton btnCambiarEstado1;
    private javax.swing.JButton btnCambiarEstado2;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnModificar2;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboRol;
    private javax.swing.JComboBox<String> cboRolB;
    private javax.swing.JComboBox<String> cboRolB1;
    private javax.swing.JComboBox<String> cboRolB3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIdUsuario;
    private javax.swing.JPanel pnlConsultarDatos;
    private javax.swing.JPanel pnlConsultarDatos1;
    private javax.swing.JPanel pnlConsultarDatos2;
    private javax.swing.JTable tblUsuario;
    private javax.swing.JTable tblUsuario1;
    private javax.swing.JTable tblUsuario2;
    private javax.swing.JScrollPane tblUsuario3;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtIdUsuario1;
    private javax.swing.JTextField txtIdUsuarioB;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtNombreUsuarioB;
    private javax.swing.JTextField txtNombreUsuarioB1;
    private javax.swing.JTextField txtNombreUsuarioB2;
    // End of variables declaration//GEN-END:variables
}
